version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    command: --bind-address=0.0.0.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: productEcommerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - /path/on/host:/var/lib/mysql

  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - "8080:8090"
    environment:
      MYSQL_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3307/productEcommerce?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      MYSQL_HOST: mysql-standalone
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone