apiVersion: v1
kind: Service
metadata:
  name: springboot-docker-service
spec:
  selector:
    app: springboot-docker-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: NodePort